/* ============================================================
   F&O INSTRUMENT MASTER AND CHAIN ANALYTICS — tests

   The chain tests work by INVERSION. A synthetic chain is built from a forward and a volatility
   smile that the test chose, every option on it is priced with bs.js, and then the analytics are
   asked to recover the inputs from the prices alone. If the engine hands back the forward and
   the smile that were used to construct the board, the derivation is right — and unlike a
   fixture copied off a screenshot, this can be run at any forward, any expiry and any skew.

   Two things get deliberate abuse:

   STALE LEGS. A real chain always has one. The forward is taken as a median across near-the-money
   strikes precisely so that a single bad quote cannot move the whole surface, so there is a test
   that pushes one leg forty points off and checks the forward does not follow it.

   MISSING DATA. Upstox's F&O master could not be fetched from this sandbox — the proxy 403s it —
   so the parser is written tolerantly and the tests cover the field spellings the existing
   loaders in server.js already accept, plus the failure modes: no lot size, a renamed field, an
   expiry that has passed. What is asserted is not that the live schema matches, but that a
   mismatch is REPORTED rather than silently producing an empty options tab.
   ============================================================ */

const { test } = require('node:test');
const assert = require('node:assert');
const BS = require('../fno/bs');
const CH = require('../fno/chain');
const createInstruments = require('../fno/instruments');

const close = (a, b, tol, msg) => assert.ok(
  Math.abs(a - b) <= tol, `${msg || 'differ'}: got ${a}, expected ${b}, |diff| ${Math.abs(a - b)} > ${tol}`);

const DAY = 86400000;
const NOW = Date.UTC(2026, 8, 15, 6, 0);            // 11:30 IST, a Tuesday
const EXPIRY = Date.UTC(2026, 8, 22);               // a week out

/* ---- the smile the tests will try to recover ----
   A realistic equity-index shape: puts bid over calls, curving up into both wings. */
const flatSmile = () => 0.13;
const skewSmile = (K, F) => {
  const m = Math.log(K / F);
  return 0.13 - 0.35 * m + 2.0 * m * m;
};

/* Build a complete synthetic chain — instrument definitions plus quotes — from a known forward
   and a known smile. Every price is generated by bs.js at the smile's own vol, so put-call
   parity holds exactly and the analytics have a right answer to be measured against. */
function makeChain(opts) {
  const o = opts || {};
  const F = o.F || 24037;
  const expiry = o.expiry || EXPIRY;
  const now = o.now || NOW;
  const r = o.r == null ? 0.065 : o.r;
  const step = o.step || 50;
  const n = o.n || 40;
  const lotSize = o.lotSize || 75;
  const smile = o.smile || (K => skewSmile(K, F));
  /* Spread is PROPORTIONAL, so the mid lands exactly on the theoretical price and the analytics
     have an exact answer to recover. Tick quantisation and empty bids are real and are tested
     separately below — mixing them into every fixture would mean no test could distinguish a
     coding error from the fixture's own rounding. */
  const halfSpreadPct = o.halfSpreadPct == null ? 0.005 : o.halfSpreadPct;
  const tick = o.tick ? 0.05 : 0;
  const oiFor = o.oi || (() => 0);
  const volFor = o.volume || (() => 0);
  const T = BS.yearsToExpiry(now, expiry);

  const centre = Math.round(F / step) * step;
  const strikes = [];
  for (let i = -n; i <= n; i++) strikes.push(centre + i * step);

  const byStrike = {}, quotes = {};
  for (const K of strikes) {
    const iv = smile(K);
    byStrike[K] = { strike: K, CE: null, PE: null };
    for (const type of ['CE', 'PE']) {
      const key = `NSE_FO|${K}${type}`;
      byStrike[K][type] = { key, tradingSymbol: `NIFTY26922${K}${type}`, lotSize, strike: K, type, expiry };
      const px = BS.price(type, F, K, T, iv, r);
      let bid = px * (1 - halfSpreadPct), ask = px * (1 + halfSpreadPct);
      if (tick) {
        bid = Math.round(bid / tick) * tick;
        ask = Math.round(ask / tick) * tick;
        if (bid < tick) { bid = 0; ask = Math.max(tick, ask); }   // an empty bid, as on a real wing
      }
      quotes[key] = { ltp: px, bid, ask, oi: oiFor(K, type), volume: volFor(K, type) };
    }
  }
  return {
    F, T, r, expiry, now, lotSize, strikes, smile,
    chain: {
      underlying: 'NIFTY', name: 'NIFTY 50', exchange: 'NSE',
      expiry, lotSize, strikes, byStrike, strikeStep: step,
      strikeCount: strikes.length, pairedStrikes: strikes.length
    },
    quotes
  };
}

/* ============================================================
   1. THE INSTRUMENT MASTER
   ============================================================ */

/* A master row in the shape the existing server.js loaders expect. */
const row = (o) => ({
  instrument_key: o.key || `NSE_FO|${o.strike || 0}${o.type || 'FUT'}`,
  trading_symbol: o.tsym || 'NIFTY26SEP24000CE',
  asset_symbol: o.asset || 'NIFTY',
  instrument_type: o.type || 'FUT',
  expiry: o.expiry === undefined ? EXPIRY : o.expiry,
  strike_price: o.strike,
  lot_size: o.lot === undefined ? 75 : o.lot,
  tick_size: 0.05,
  segment: 'NSE_FO'
});

function masterFor(strikes, extra) {
  const rows = [];
  for (const k of strikes) {
    rows.push(row({ strike: k, type: 'CE', key: `NSE_FO|${k}CE` }));
    rows.push(row({ strike: k, type: 'PE', key: `NSE_FO|${k}PE` }));
  }
  rows.push(row({ type: 'FUT', key: 'NSE_FO|NIFTYFUT' }));
  return rows.concat(extra || []);
}

const instFrom = (nseRows, bseRows) => createInstruments({
  cacheFile: null, now: () => NOW,
  files: { NSE_FO: nseRows || [], BSE_FO: bseRows || [] }
});

test('the master parses into underlying → expiry → strike, with the lot size taken from the data', () => {
  const I = instFrom(masterFor([23900, 23950, 24000, 24050]));
  const res = I.load();
  return res.then(r => {
    assert.ok(r.available, r.reason);
    const c = I.chain(r.data, 'NIFTY', EXPIRY);
    assert.ok(c, 'the expiry is listed');
    assert.equal(c.lotSize, 75, 'the lot size came from the master, not from a constant');
    assert.deepEqual(c.strikes, [23900, 23950, 24000, 24050], 'strikes are sorted');
    assert.equal(c.strikeStep, 50, 'the strike step is inferred');
    assert.equal(c.pairedStrikes, 4, 'every strike has both legs');
    assert.ok(c.byStrike[24000].CE.key && c.byStrike[24000].PE.key);
    assert.equal(r.data.underlyings.NIFTY.futures.length, 1, 'the futures ladder is kept too');
  });
});

test('no lot size means the contract is DROPPED, never defaulted', () => {
  /* Every position size, margin estimate and rupee of projected P&L scales linearly off the lot
     size. Filling in a plausible-looking default would misstate risk silently and indefinitely —
     the failure mode this whole file is arranged to prevent. */
  return instFrom(masterFor([24000]).concat([
    row({ strike: 24100, type: 'CE', key: 'NSE_FO|24100CE', lot: null }),
    row({ strike: 24100, type: 'PE', key: 'NSE_FO|24100PE', lot: null })
  ])).load().then(r => {
    const c = r.data.underlyings.NIFTY.expiries[0];
    assert.ok(!c.strikes.includes(24100), 'the lot-less strike is not listed');
    assert.ok(r.data.warnings.some(w => /no readable lot size/.test(w)), 'and the drop is reported: ' + JSON.stringify(r.data.warnings));
  });
});

test('two lot sizes inside one expiry raises a warning instead of being picked silently', () => {
  /* This is what a mid-cycle lot-size revision looks like in a master, and quietly choosing one
     would halve or double every position size on that expiry. */
  const rows = masterFor([24000, 24050]).concat([
    row({ strike: 24100, type: 'CE', key: 'NSE_FO|24100CE', lot: 50 }),
    row({ strike: 24100, type: 'PE', key: 'NSE_FO|24100PE', lot: 50 })
  ]);
  return instFrom(rows).load().then(r => {
    assert.ok(r.data.warnings.some(w => /different lot sizes/.test(w)), JSON.stringify(r.data.warnings));
    // It still ships a usable chain, using the most common size.
    assert.equal(r.data.underlyings.NIFTY.expiries[0].lotSize, 75, 'the majority lot size is used');
  });
});

test('a renamed field is reported, not silently swallowed', () => {
  /* The sandbox cannot reach Upstox, so the live schema is unverified. What CAN be guaranteed is
     that a schema change surfaces on the dashboard rather than presenting an empty options tab
     as though the market had no contracts listed. */
  const broken = masterFor([24000]).map(x => {
    const { asset_symbol, ...rest } = x;
    return { ...rest, underlying: asset_symbol };          // a spelling the parser does not know
  });
  return instFrom(broken).load().then(r => {
    assert.equal(r.available, false, 'nothing parsed, so nothing is claimed');
    assert.match(r.reason, /schema has probably changed/i);
  });
});

test('the parser accepts the field spellings the existing server loaders already accept', () => {
  const variants = [
    { instrumentKey: 'X|1', tradingsymbol: 'A', underlying_symbol: 'NIFTY', instrumentType: 'CE', expiry: String(EXPIRY), strikePrice: 24000, lotSize: 75 },
    { instrument_key: 'X|2', name: 'NIFTY', instrument_type: 'PE', expiry_date: '2026-09-22', strike: 24000, lot_size: 75 },
    { instrument_key: 'X|3', asset_symbol: 'NIFTY', option_type: 'CALL', expiry: Math.floor(EXPIRY / 1000), strike_price: 24100, lot_size: 75 }
  ];
  const I = createInstruments({ cacheFile: null, now: () => NOW, files: { NSE_FO: variants, BSE_FO: [] } });
  return I.load().then(r => {
    assert.ok(r.available, r.reason);
    const exps = I.expiries(r.data, 'NIFTY');
    assert.ok(exps.length >= 1, 'contracts were recognised through alternate spellings');
    const all = r.data.underlyings.NIFTY.expiries.flatMap(e => e.strikes);
    assert.ok(all.includes(24000) && all.includes(24100), 'strikes came through: ' + JSON.stringify(all));
  });
});

test('expiry timestamps are read as milliseconds, seconds or a date string', () => {
  const P = createInstruments.__parseExpiry;
  assert.equal(P(EXPIRY), EXPIRY, 'milliseconds pass through');
  assert.equal(P(Math.floor(EXPIRY / 1000)), EXPIRY, 'seconds are scaled up');
  assert.equal(P(String(EXPIRY)), EXPIRY, 'a numeric string is still a number');
  assert.equal(P('2026-09-22'), Date.UTC(2026, 8, 22), 'an ISO date parses');
  assert.equal(P(''), null);
  assert.equal(P(null), null);
  assert.equal(P('not a date'), null);
  assert.equal(P(0), null, 'a zero expiry is missing data, not the epoch');
});

test('expired contracts are filtered out and a minimum life can be required', () => {
  const rows = masterFor([24000])
    .concat(masterFor([24000]).map(x => ({ ...x, instrument_key: x.instrument_key + 'B', expiry: NOW - 2 * DAY })))
    .concat(masterFor([24000]).map(x => ({ ...x, instrument_key: x.instrument_key + 'C', expiry: NOW + 3600000 })));
  const I = instFrom(rows);
  return I.load().then(r => {
    const all = I.expiries(r.data, 'NIFTY');
    assert.ok(all.every(e => e.expiry > NOW), 'nothing already expired is offered');
    assert.ok(all.some(e => e.daysLeft < 1), 'the one expiring in an hour is present by default');

    /* On expiry afternoon the front contract is a different instrument in practice — its Greeks
       are meaningless and its spread is enormous. A caller must be able to skip it. */
    const usable = I.expiries(r.data, 'NIFTY', { minHoursLeft: 6 });
    assert.ok(usable.every(e => e.daysLeft > 0.25), 'the near-dead expiry is excluded on request');
    assert.ok(usable.length < all.length);
  });
});

test('quote keys are windowed around the money rather than requesting the whole board', () => {
  const strikes = []; for (let k = 22000; k <= 26000; k += 50) strikes.push(k);
  const I = instFrom(masterFor(strikes));
  return I.load().then(r => {
    const c = I.chain(r.data, 'NIFTY', EXPIRY);
    assert.equal(I.nearestStrike(c, 24037), 24050, 'the nearest strike to the forward');
    const keys = I.quoteKeys(c, 24037, 10);
    assert.equal(keys.length, 21 * 2, 'ten either side, both legs');
    assert.ok(keys.includes('NSE_FO|24050CE') && keys.includes('NSE_FO|24050PE'));
    assert.ok(!keys.includes('NSE_FO|22000CE'), 'the far wing is not quoted');
    assert.ok(keys.length < strikes.length * 2, 'far fewer than the full board');
  });
});

test('an unreachable master reports unavailable with a reason, never an empty chain', () => {
  const I = createInstruments({
    cacheFile: null, now: () => NOW,
    fetchImpl: async () => { throw new Error('403 from the proxy'); }
  });
  return I.load().then(r => {
    assert.equal(r.available, false);
    assert.ok(/could not download/.test(r.reason), r.reason);
    assert.equal(r.data, null, 'no data is better than invented data');
    assert.deepEqual(I.expiries(null, 'NIFTY'), [], 'accessors tolerate the absence');
    assert.equal(I.chain(null, 'NIFTY', EXPIRY), null);
  });
});

/* ============================================================
   2. THE FORWARD
   ============================================================ */

test('the forward is recovered from the chain to within a fraction of a point', () => {
  for (const F of [24037, 52310, 81455]) {
    const m = makeChain({ F, step: F > 50000 ? 100 : 50 });
    const a = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });
    assert.ok(a.ok, a.reason);
    close(a.forward, F, 0.01, `forward at F=${F}`);
    assert.equal(a.forwardDetail.quality, 'tight', 'a clean chain agrees on the forward');
    assert.ok(a.forwardDetail.strikesUsed >= 3, 'several strikes contributed');
  }
});

test('the forward is derived without any spot input at all', () => {
  /* The point of using parity: no dividend yield to guess, no index level to trust. The chain
     bootstraps its own at-the-money from the quotes alone. */
  const m = makeChain({ F: 24037 });
  const a = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });   // no spotHint
  close(a.forward, 24037, 0.01, 'forward with no hint');
  // And supplying a badly wrong hint does not drag it off, because the hint only seeds the band.
  const b = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r, spotHint: 23500 });
  close(b.forward, 24037, 0.5, 'forward is not captured by a poor hint');
});

test('one stale leg does not move the forward — the reason it is a median', () => {
  const m = makeChain({ F: 24037 });
  const atmCall = m.chain.byStrike[24050].CE.key;
  const before = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r }).forward;

  // A call forty points behind the rest of the board: one leg that has not printed in ten minutes.
  const q = { ...m.quotes };
  q[atmCall] = { ...q[atmCall], ltp: q[atmCall].ltp + 40, bid: q[atmCall].bid + 40, ask: q[atmCall].ask + 40 };
  const after = CH.analyse({ chain: m.chain, quotes: q, now: m.now, r: m.r });

  close(after.forward, before, 1, 'the median absorbs the outlier');
  assert.ok(Math.abs(after.forward - before) < 5, 'and certainly does not follow it forty points');
  // The inconsistency still shows up where it should: in the parity implied-vol gap.
  assert.ok(after.quality.parityIvGap > 0, 'the bad leg is visible in the quality block');
});

test('a chain whose legs disagree is marked suspect rather than reported as fact', () => {
  const m = makeChain({ F: 24037 });
  const q = {};
  // Shift every call up and every put down: parity broken across the board, as in a fast open.
  for (const [k, v] of Object.entries(m.quotes)) {
    const bump = /CE$/.test(k) ? 30 : -30;
    q[k] = { ...v, ltp: Math.max(0.05, v.ltp + bump), bid: Math.max(0.05, v.bid + bump), ask: Math.max(0.1, v.ask + bump) };
  }
  const a = CH.analyse({ chain: m.chain, quotes: q, now: m.now, r: m.r });
  assert.ok(a.ok, 'it still returns something usable');
  assert.ok(a.forwardDetail.dispersionPct > 0, 'dispersion is measured');
  assert.ok(a.quality.warnings.length > 0, 'and the caller is warned');
});

/* ============================================================
   3. THE VOLATILITY SURFACE
   ============================================================ */

test('the implied volatility smile is recovered from the prices', () => {
  const m = makeChain({ F: 24037 });
  const a = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });
  assert.ok(a.surface.length > 20, `expected a populated surface, got ${a.surface.length}`);
  let worst = 0;
  for (const pt of a.surface) {
    const want = m.smile(pt.strike);
    worst = Math.max(worst, Math.abs(pt.iv - want));
  }
  assert.ok(worst < 1e-4, `smile recovered to ${worst.toExponential(2)} — expected better than 1e-4`);
});

test('the surface is built from out-of-the-money options only', () => {
  /* Parity means the in-the-money twin carries no extra information and arrives through a much
     worse quote. Using the OTM side is standard practice and it keeps a stale deep-ITM print
     from manufacturing a vol spike on the wing. */
  const m = makeChain({ F: 24037 });
  const a = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });
  for (const pt of a.surface) {
    if (pt.strike > a.forward) assert.equal(pt.source, 'CE', `strike ${pt.strike} above the forward should use the call`);
    if (pt.strike < a.forward) assert.equal(pt.source, 'PE', `strike ${pt.strike} below the forward should use the put`);
  }
  assert.ok(a.surface.some(p => p.source === 'CE') && a.surface.some(p => p.source === 'PE'), 'both halves are represented');
});

test('at-the-money implied vol is interpolated at the forward, not read off the nearest strike', () => {
  /* With a 50-point strike step the nearest strike can sit 25 points from the forward, and on a
     steep smile that is a real difference. Tested against a deliberately steep one. */
  const F = 24025;                                    // exactly between two strikes
  const steep = K => 0.13 - 1.2 * Math.log(K / F);
  const m = makeChain({ F, smile: steep });
  const a = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });
  close(a.atmIv, 0.13, 2e-3, 'ATM vol at the forward');

  // Reading the nearest strike instead would have been noticeably wrong.
  const nearest = a.surface.find(p => p.strike === a.atmStrike);
  assert.ok(Math.abs(nearest.iv - 0.13) > Math.abs(a.atmIv - 0.13), 'interpolation beats the nearest strike here');
});

test('the expected move comes from the straddle and agrees with the implied vol', () => {
  const m = makeChain({ F: 24000, smile: flatSmile });      // forward on a strike, flat smile
  const a = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });
  assert.equal(a.expectedMove.basis, 'ATM straddle');
  const fromIv = BS.expectedMove(a.forward, a.T, a.atmIv);
  // The straddle and the formula are two routes to the same number.
  assert.ok(Math.abs(a.expectedMove.points - fromIv.points) / fromIv.points < 0.01,
    `straddle ${a.expectedMove.points.toFixed(1)} vs vol-implied ${fromIv.points.toFixed(1)}`);
  /* Sanity on the magnitude, which is the check a relative test cannot make: a week at 13%
     annualised vol is 13% x sqrt(7/365) = 1.8% of a standard deviation, so about 430 points on
     24000, and the MEAN ABSOLUTE move is sqrt(2/pi) of that — around 345. */
  assert.ok(a.expectedMove.points > 250 && a.expectedMove.points < 450, `implausible expected move ${a.expectedMove.points}`);
  close(a.expectedMove.points, 345, 25, 'a week of 13% vol on NIFTY');
  close(a.expectedMove.pct, a.expectedMove.points / a.forward, 1e-9);
});

test('skew is measured at the 25-delta strikes and reads zero on a flat smile', () => {
  const flat = CH.analyse({ ...chainArgs(makeChain({ F: 24037, smile: flatSmile })) });
  assert.ok(flat.skew, 'a 25-delta risk reversal was computed');
  close(flat.skew.rr25, 0, 2e-3, 'a flat smile has no skew');
  close(flat.skew.butterfly25, 0, 2e-3, 'and no curvature');

  /* The 25-delta strikes on a SEVEN-DAY option sit barely 1.2% either side of the money — short
     expiries compress the whole delta ladder into a narrow band — so a skew slope that would
     give several vol points on a quarterly gives under one point here. That is the real number,
     and the assertion below against the constructed smile is what pins it. */
  const skewed = CH.analyse({ ...chainArgs(makeChain({ F: 24037 })) });
  assert.ok(skewed.skew.rr25 > 0.005, `a put-skewed board should price puts over calls, got ${skewed.skew.rr25}`);
  assert.ok(Math.abs(skewed.skew.put25.strike / skewed.forward - 1) < 0.03, 'the 25-delta strikes are close to the money on a weekly');
  assert.ok(skewed.skew.put25.strike < skewed.forward, 'the 25-delta put is below the market');
  assert.ok(skewed.skew.call25.strike > skewed.forward, 'the 25-delta call is above it');
  // The measured risk reversal must match the smile it was built from.
  const wantRR = skewSmile(skewed.skew.put25.strike, 24037) - skewSmile(skewed.skew.call25.strike, 24037);
  close(skewed.skew.rr25, wantRR, 5e-3, 'risk reversal matches the constructed smile');
  // A 0.35 smile slope is a mild bias and must be described as one, not as a panic.
  assert.ok(/normal mild put bias/.test(skewed.skew.reading), skewed.skew.reading);

  // A genuinely steep board reads as one.
  const steep = CH.analyse({ ...chainArgs(makeChain({ F: 24037, smile: K => 0.13 - 1.4 * Math.log(K / 24037) })) });
  assert.ok(/paying up for puts/.test(steep.skew.reading), steep.skew.reading);
  assert.ok(steep.skew.slope > skewed.skew.slope, 'a steeper smile reports a steeper slope');
});

test('skew is normalised so a weekly and a quarterly can be compared on one scale', () => {
  /* The 25-delta band spans 0.46% of the index on a one-day option and 4.58% on a quarterly, so
     the SAME underlying smile produces raw risk reversals an order of magnitude apart. A fixed
     threshold on the raw number would be unreachable on a weekly during a genuine panic and
     would trigger on a quarterly in a dead market. Dividing by atmIv·√T recovers the smile
     slope, which is the quantity that means the same thing at every maturity. */
  const F = 24037;
  const smile = K => 0.13 - 0.9 * Math.log(K / F);
  const results = [];
  for (const days of [7, 30, 90]) {
    const m = makeChain({ F, smile, expiry: NOW + days * DAY, step: 50, n: 90 });
    const a = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });
    assert.ok(a.skew, `${days}d chain produced a skew`);
    results.push({ days, rr25: a.skew.rr25, slope: a.skew.slope, reading: a.skew.reading });
  }
  const fmt = results.map(r => `${r.days}d rr25=${r.rr25.toFixed(4)} slope=${r.slope.toFixed(3)}`).join('  ');

  // The raw risk reversal grows several-fold with maturity...
  assert.ok(results[2].rr25 > results[0].rr25 * 2.5, `raw RR should scale with √T: ${fmt}`);
  // ...while the normalised slope stays put, which is the entire point of normalising.
  for (const r of results) close(r.slope, results[0].slope, 0.15, `normalised slope at ${r.days}d — ${fmt}`);
  // And so every maturity reaches the same verdict about the same market.
  assert.equal(new Set(results.map(r => r.reading)).size, 1, 'one market, one reading: ' + fmt);
});

test('a chain too narrow to reach 25 delta reports no skew rather than a wrong one', () => {
  // Only strikes right around the money — nothing out at 25 delta to measure.
  const m = makeChain({ F: 24037, n: 1 });
  const a = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });
  assert.ok(a.ok);
  assert.equal(a.skew, null, 'no 25-delta strikes listed means no 25-delta skew');
});

/* ============================================================
   4. POSITIONING
   ============================================================ */

test('max pain minimises the total payout, verified against an independent sweep', () => {
  const oi = (K, type) => (type === 'CE' ? Math.max(0, 200 - Math.abs(K - 24200) / 50 * 10)
    : Math.max(0, 200 - Math.abs(K - 23800) / 50 * 10));
  const m = makeChain({ F: 24037, oi, n: 15 });
  const a = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });
  assert.ok(a.maxPain, 'max pain computed');

  // Recompute the payout curve here, from the definition, and confirm the reported strike is the
  // argmin. Reimplementing it in the test is what makes this a check rather than a restatement.
  let best = null, bestPay = Infinity;
  for (const P of m.strikes) {
    let pay = 0;
    for (const K of m.strikes) {
      if (P > K) pay += oi(K, 'CE') * (P - K);
      if (P < K) pay += oi(K, 'PE') * (K - P);
    }
    if (pay < bestPay) { bestPay = pay; best = P; }
  }
  assert.equal(a.maxPain.strike, best, 'max pain agrees with an independent sweep');
  close(a.maxPain.payout, bestPay * m.lotSize, 1, 'payout is in rupees, scaled by the lot size');
  assert.ok(/descriptive only/.test(a.maxPain.caveat), 'it is labelled for what it is');
});

test('the put-call ratio and OI walls are computed, and carry their caveats', () => {
  const oi = (K, type) => type === 'PE' ? 200 : 100;      // puts at twice the calls
  const m = makeChain({ F: 24037, oi, n: 10 });
  const a = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });
  close(a.pcr.oi, 2, 1e-9, 'put-call ratio by open interest');
  assert.ok(/weak on its own/.test(a.pcr.caveat));

  const walls = a.oiWalls;
  assert.ok(walls.resistance.length && walls.support.length, 'walls on both sides');
  assert.ok(walls.resistance.every(w => w.strike > a.forward), 'resistance sits above the market');
  assert.ok(walls.support.every(w => w.strike < a.forward), 'support sits below it');
  assert.ok(/not the same as levels it cannot pass/.test(walls.caveat));
});

test('no open interest in the feed means those three are unavailable, not zero', () => {
  const m = makeChain({ F: 24037, n: 8 });               // oi defaults to 0 everywhere
  const q = {};
  for (const [k, v] of Object.entries(m.quotes)) { const { oi, ...rest } = v; q[k] = rest; }
  const a = CH.analyse({ chain: m.chain, quotes: q, now: m.now, r: m.r });
  assert.ok(a.ok, 'the rest of the chain still works');
  assert.equal(a.pcr, null, 'no ratio invented from nothing');
  assert.equal(a.maxPain, null);
  assert.equal(a.oiWalls, null);
  assert.equal(a.quality.haveOpenInterest, false);
  assert.ok(a.quality.warnings.some(w => /open interest/.test(w)), 'and the absence is stated');
});

/* ============================================================
   5. LIQUIDITY AND DATA QUALITY
   ============================================================ */

test('wide strikes are flagged as untradeable and tight ones are not', () => {
  const m = makeChain({ F: 24037, n: 12, halfSpreadPct: 0.005 });
  const a = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });
  const atm = a.rows.find(x => x.strike === a.atmStrike);
  assert.equal(atm.CE.tradeable, true, 'a 1% spread near the money is tradeable');
  assert.equal(atm.CE.liquidityNote, null);

  const wide = makeChain({ F: 24037, n: 12, halfSpreadPct: 0.12 });
  const b = CH.analyse({ chain: wide.chain, quotes: wide.quotes, now: wide.now, r: wide.r });
  const wAtm = b.rows.find(x => x.strike === b.atmStrike);
  assert.equal(wAtm.CE.tradeable, false, 'a 24% spread is not');
  assert.ok(/round trip alone is a large loss/.test(wAtm.CE.liquidityNote), wAtm.CE.liquidityNote);
  assert.ok(b.quality.medianSpreadPct > a.quality.medianSpreadPct);
});

test('a chain priced only off last-traded prices says so', () => {
  /* An LTP is a historical fact that may be an hour old. A board with no live two-sided quotes
     can still be analysed, but nothing downstream should treat its spreads as known. */
  const m = makeChain({ F: 24037, n: 10 });
  const q = {};
  for (const [k, v] of Object.entries(m.quotes)) q[k] = { ltp: v.ltp, oi: v.oi };
  const a = CH.analyse({ chain: m.chain, quotes: q, now: m.now, r: m.r });
  assert.ok(a.ok);
  assert.equal(a.quality.onMid, 0);
  assert.ok(a.quality.midShare < 0.5);
  assert.ok(a.quality.warnings.some(w => /last-traded prices/.test(w)), JSON.stringify(a.quality.warnings));
  assert.equal(a.quality.medianSpreadPct, null, 'spread is unknown, not zero');
});

test('a zero bid is not treated as half a price', () => {
  /* Far strikes quote 0.00 / 0.05 all day. Treating that as a 0.025 mid feeds a fictional
     premium into the vol surface and is how phantom "cheap" strikes appear. */
  assert.equal(CH.quoteValue({ bid: 0, ask: 0.05 }).src, 'no-bid');
  assert.equal(CH.quoteValue({ bid: 18, ask: 19.5 }).src, 'mid');
  close(CH.quoteValue({ bid: 18, ask: 19.5 }).px, 18.75, 1e-12);
  assert.equal(CH.quoteValue({ ltp: 12 }).src, 'ltp');
  assert.equal(CH.quoteValue({ bid: 0, ask: 0 }), null, 'no quote at all');
  assert.equal(CH.quoteValue(null), null);
  // A no-bid strike is excluded from the forward derivation entirely.
  const m = makeChain({ F: 24037, n: 6 });
  const q = { ...m.quotes };
  for (const k of Object.keys(q)) if (/24[23]\d\dCE/.test(k)) q[k] = { bid: 0, ask: 0.05, ltp: 0.03 };
  const a = CH.analyse({ chain: m.chain, quotes: q, now: m.now, r: m.r });
  close(a.forward, 24037, 1, 'no-bid strikes do not distort the forward');
});

test('calls and puts disagreeing on implied vol is surfaced as a feed problem', () => {
  /* Parity forces a call and a put on the same strike to imply the same volatility. Where they
     do not, one quote is stale — the most direct read available on feed health. */
  const m = makeChain({ F: 24037, n: 10 });
  const clean = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });
  assert.ok(clean.quality.parityIvGap < 1e-4, `a consistent board has no gap, got ${clean.quality.parityIvGap}`);
  assert.equal(clean.quality.parityIvGapNote, null);

  const q = { ...m.quotes };
  for (const k of Object.keys(q)) if (/CE$/.test(k)) q[k] = { ...q[k], bid: q[k].bid * 1.25, ask: q[k].ask * 1.25, ltp: q[k].ltp * 1.25 };
  const bad = CH.analyse({ chain: m.chain, quotes: q, now: m.now, r: m.r });
  assert.ok(bad.quality.parityIvGap > 0.01, `expected a visible gap, got ${bad.quality.parityIvGap}`);
  assert.ok(/put-call parity/.test(bad.quality.parityIvGapNote), bad.quality.parityIvGapNote);
});

/* ============================================================
   6. REFUSALS
   ============================================================ */

test('the analyser refuses rather than guessing when it cannot proceed', () => {
  const m = makeChain({ F: 24037, n: 4 });

  const expired = CH.analyse({ chain: m.chain, quotes: m.quotes, now: EXPIRY + DAY, r: m.r });
  assert.equal(expired.ok, false);
  assert.match(expired.reason, /passed|final minute/i);

  const noLot = CH.analyse({ chain: { ...m.chain, lotSize: null }, quotes: m.quotes, now: m.now });
  assert.equal(noLot.ok, false);
  assert.match(noLot.reason, /lot size/i, 'no lot size means no position sizing, so nothing is reported');

  const noQuotes = CH.analyse({ chain: m.chain, quotes: {}, now: m.now });
  assert.equal(noQuotes.ok, false);
  assert.match(noQuotes.reason, /usable quote/i);

  assert.equal(CH.analyse({}).ok, false);
  assert.equal(CH.analyse(null).ok, false);

  // Calls quoted but no puts at all: parity has nothing to work with, and it says so.
  const callsOnly = {};
  for (const [k, v] of Object.entries(m.quotes)) if (/CE$/.test(k)) callsOnly[k] = v;
  const oneSided = CH.analyse({ chain: m.chain, quotes: callsOnly, now: m.now, r: m.r });
  assert.equal(oneSided.ok, false);
  assert.match(oneSided.reason, /both a call and a put/i);
});

test('every strike carries Greeks computed at its OWN implied vol', () => {
  /* Using one blended volatility across the board would misprice the wings, which is exactly
     where position sizing goes wrong. Each strike's delta is priced on the smile's value there. */
  const m = makeChain({ F: 24037, n: 12 });
  const a = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });
  for (const row of a.rows) {
    const leg = row.strike >= a.forward ? row.CE : row.PE;
    if (!leg || !leg.iv) continue;
    const want = BS.black76({ type: leg === row.CE ? 'CE' : 'PE', F: a.forward, K: row.strike, T: a.T, sigma: leg.iv, r: a.r });
    close(leg.delta, want.delta, 1e-9, `delta at ${row.strike}`);
    close(leg.vega, want.vega, 1e-6, `vega at ${row.strike}`);
    assert.ok(isFinite(leg.thetaDay) && isFinite(leg.decay1d), 'decay numbers are present');
  }
  /* Delta falls as the strike rises — for calls from +df down to 0, for puts from 0 down to −df.
     The surface interleaves the two, so it is a sawtooth overall and each side must be checked
     on its own. (Asserting a single monotone run across the whole surface would be asserting
     something false about the put wing.) */
  for (const side of ['CE', 'PE']) {
    const pts = a.surface.filter(p => p.source === side);
    for (let i = 1; i < pts.length; i++) {
      assert.ok(pts[i].delta <= pts[i - 1].delta + 1e-9,
        `${side} delta should fall as the strike rises: ${pts[i - 1].strike}→${pts[i - 1].delta}, ${pts[i].strike}→${pts[i].delta}`);
    }
  }
  const calls = a.surface.filter(p => p.source === 'CE');
  const puts = a.surface.filter(p => p.source === 'PE');
  assert.ok(calls.every(p => p.delta > 0) && puts.every(p => p.delta < 0), 'the two wings carry opposite signs');
});

test('tick quantisation and empty bids are handled without corrupting the surface', () => {
  /* The realistic fixture: prices rounded to the 0.05 tick, and far wings quoted 0.00 / 0.05
     with no bid at all. The forward and the at-the-money vol must survive it, and the fabricated
     "half of an offer" price on a no-bid strike must not reach the vol curve. */
  const m = makeChain({ F: 24037, n: 30, tick: true });
  const a = CH.analyse({ chain: m.chain, quotes: m.quotes, now: m.now, r: m.r });
  assert.ok(a.ok, a.reason);
  close(a.forward, 24037, 2, 'the forward survives tick rounding');
  close(a.atmIv, m.smile(a.forward), 0.005, 'at-the-money vol survives it too');

  const noBidStrikes = a.rows.filter(row => {
    const leg = row.strike >= a.forward ? row.CE : row.PE;
    return leg && leg.q && leg.q.src === 'no-bid';
  }).map(r => r.strike);
  assert.ok(noBidStrikes.length > 0, 'the fixture produced some empty bids, as a real wing does');
  for (const k of noBidStrikes) {
    assert.ok(!a.surface.some(p => p.strike === k),
      `strike ${k} has no bid — half of an offer is not a price the market agreed to, so it must not reach the vol surface`);
  }
});

function chainArgs(m) { return { chain: m.chain, quotes: m.quotes, now: m.now, r: m.r }; }
