"use client";

import { useCallback, useEffect, useState } from "react";

import { get, patch, post, type BrandBrain } from "@/lib/api";
import { Bar, Confidence, Empty, ErrorNote, Section, Spinner } from "@/components/ui";

export default function BrandPage() {
  const [brand, setBrand] = useState<BrandBrain | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [note, setNote] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ description: "", positioning: "" });

  const load = useCallback(async () => {
    try {
      const data = await get<BrandBrain>("/api/v1/brands");
      setBrand(data);
      setForm({ description: data.description ?? "", positioning: data.positioning ?? "" });
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load the Brand Brain");
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  async function save() {
    setBusy(true);
    try {
      await patch("/api/v1/brands", form);
      setNote("Brand Brain updated");
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Save failed");
    } finally {
      setBusy(false);
    }
  }

  async function regenerate() {
    setBusy(true);
    setNote(null);
    try {
      await post("/api/v1/strategy/brand", {});
      setNote("Brand strategy regenerated by the Brand Strategist agent");
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Regeneration failed");
    } finally {
      setBusy(false);
    }
  }

  if (!brand) return error ? <ErrorNote error={error} /> : <Spinner />;

  const servicesByCategory = brand.services.reduce<Record<string, typeof brand.services>>(
    (acc, service) => {
      (acc[service.category] ??= []).push(service);
      return acc;
    },
    {},
  );

  return (
    <div className="mx-auto max-w-5xl space-y-6">
      <header className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <p className="label">Brand Brain</p>
          <h1 className="mt-1 font-display text-3xl text-sand">{brand.name}</h1>
          <p className="mt-1 text-sm text-muted">
            {brand.website} · @{brand.instagram_handle}
          </p>
        </div>
        <button onClick={regenerate} disabled={busy} className="btn-ghost">
          {busy ? "Working…" : "Regenerate strategy"}
        </button>
      </header>

      <ErrorNote error={error} />
      {note && (
        <p className="rounded-lg border border-emerald-900/50 bg-emerald-950/20 px-3 py-2 text-sm text-emerald-300">
          {note}
        </p>
      )}

      {/* Completeness first: it tells the client what to do next. */}
      <Section
        title="Completeness"
        subtitle="Every gap here narrows what the AI is allowed to say about your salon."
      >
        <div className="mb-2 flex items-baseline justify-between">
          <span className="font-display text-3xl text-sand">{brand.completeness}%</span>
          <span className="text-sm text-muted">{brand.missing_fields.length} fields missing</span>
        </div>
        <Bar value={brand.completeness} max={100} />
        {brand.missing_fields.length > 0 && (
          <div className="mt-4 flex flex-wrap gap-2">
            {brand.missing_fields.map((field) => (
              <span key={field} className="chip border-amber-900/60 text-amber-300">
                {field.replace(/_/g, " ")}
              </span>
            ))}
          </div>
        )}
      </Section>

      <Section title="Identity" subtitle="Edit anything here — the AI reasons only from this.">
        <div className="space-y-4">
          <div>
            <label className="label" htmlFor="description">Description</label>
            <textarea
              id="description" rows={3} className="input mt-1.5"
              value={form.description}
              onChange={(e) => setForm({ ...form, description: e.target.value })}
            />
          </div>
          <div>
            <label className="label" htmlFor="positioning">Positioning</label>
            <textarea
              id="positioning" rows={4} className="input mt-1.5"
              value={form.positioning}
              onChange={(e) => setForm({ ...form, positioning: e.target.value })}
            />
          </div>
          <button onClick={save} disabled={busy} className="btn-primary">Save</button>
        </div>
      </Section>

      <div className="grid gap-6 lg:grid-cols-2">
        <Section title="Services" subtitle={`${brand.services.length} services — no price is recorded`}>
          <div className="space-y-4">
            {Object.entries(servicesByCategory).map(([category, services]) => (
              <div key={category}>
                <p className="label">{category}</p>
                <ul className="mt-1.5 space-y-1">
                  {services.map((service) => (
                    <li key={service.id} className="flex items-center justify-between gap-2 text-sm">
                      <span className="text-sand">{service.name}</span>
                      <span className="chip shrink-0 border-amber-900/60 text-amber-300">
                        {service.price === null ? "price unknown" : service.price}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </Section>

        <div className="space-y-6">
          <Section title="Products" subtitle="The only brands the AI may name">
            <div className="flex flex-wrap gap-2">
              {brand.products.map((product) => (
                <span key={product.id} className="chip border-emerald-900 text-emerald-300">
                  {product.brand_name}
                </span>
              ))}
            </div>
          </Section>

          <Section title="Locations">
            {brand.locations.length === 0 ? <Empty>No location recorded.</Empty> : (
              <ul className="space-y-2">
                {brand.locations.map((loc, i) => (
                  <li key={i} className="rounded-lg border border-ink-800 p-3 text-sm">
                    <p className="text-sand">{loc.address}</p>
                    <p className="text-muted">{loc.city}, {loc.state}</p>
                    <p className="mt-1 text-xs text-muted">{loc.hours}</p>
                    <div className="mt-2"><Confidence level={loc.confidence ?? "unknown"} /></div>
                  </li>
                ))}
              </ul>
            )}
          </Section>
        </div>
      </div>

      <Section title="Content pillars" subtitle="Discovered and reweighted by the AI — not hard-coded">
        <div className="space-y-3">
          {brand.pillars.map((pillar) => (
            <div key={pillar.id}>
              <div className="mb-1 flex items-baseline justify-between gap-3">
                <div>
                  <span className="text-sm text-sand">{pillar.label}</span>
                  <span className="ml-2 chip">{pillar.source.replace(/_/g, " ")}</span>
                </div>
                <span className="text-sm text-muted">{Math.round(pillar.weight * 100)}%</span>
              </div>
              <Bar value={pillar.weight} max={1} />
              {pillar.description && <p className="mt-1 text-xs text-muted">{pillar.description}</p>}
            </div>
          ))}
        </div>
      </Section>

      <Section title="Audiences">
        <div className="grid gap-3 md:grid-cols-3">
          {brand.audiences.map((audience) => (
            <div key={audience.id} className="rounded-lg border border-ink-800 p-3">
              <div className="flex items-start justify-between gap-2">
                <p className="text-sm font-medium text-sand">{audience.segment}</p>
                <Confidence level={audience.confidence} />
              </div>
              <p className="mt-2 label">Pains</p>
              <ul className="mt-1 list-disc pl-4 text-xs text-muted">
                {audience.pains.map((pain) => <li key={pain}>{pain}</li>)}
              </ul>
            </div>
          ))}
        </div>
      </Section>

      <div className="grid gap-6 lg:grid-cols-2">
        <Section title="Words to avoid">
          <div className="flex flex-wrap gap-2">
            {brand.words_to_avoid.map((word) => (
              <span key={word} className="chip border-red-900/60 text-red-300">{word}</span>
            ))}
          </div>
        </Section>

        <Section title="Claims to avoid">
          <ul className="list-disc space-y-1 pl-5 text-sm text-muted">
            {brand.claims_to_avoid.map((claim) => <li key={claim}>{claim}</li>)}
          </ul>
        </Section>
      </div>

      <Section
        title="Unknown — never asserted"
        subtitle="The system will not invent any of these. Fill them in to unlock better content."
      >
        <div className="flex flex-wrap gap-2">
          {brand.unknown_fields.map((field) => (
            <span key={field} className="chip border-red-900/50 text-red-300/80">
              {field.replace(/_/g, " ")}
            </span>
          ))}
        </div>
        {brand.provenance?.research_note && (
          <p className="mt-4 rounded-lg border border-ink-800 bg-ink-950/60 p-3 text-xs leading-relaxed text-muted">
            {brand.provenance.research_note}
          </p>
        )}
      </Section>
    </div>
  );
}
