"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-28 19:27:22.543024
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # referenced by the JSONB astext_type below
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('supabase_uid', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_supabase_uid'), ['supabase_uid'], unique=True)

    op.create_table('ai_activity_log',
    sa.Column('agent', sa.String(length=60), nullable=False),
    sa.Column('task', sa.String(length=120), nullable=False),
    sa.Column('input_digest', sa.String(length=64), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_activity_log_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_activity_log_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_activity_log_content_item_id'), ['content_item_id'], unique=False)
        batch_op.create_index('ix_ai_log_agent_time', ['agent', 'created_at'], unique=False)
        batch_op.create_index('ix_ai_log_client_time', ['client_id', 'created_at'], unique=False)

    op.create_table('ai_insights',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_insights_client_id'), ['client_id'], unique=False)

    op.create_table('assets',
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('footage_type', sa.String(length=24), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('analysis', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('shoot_group', sa.String(length=120), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_footage_type'), ['footage_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_shoot_group'), ['shoot_group'], unique=False)

    op.create_table('audit_logs',
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)

    op.create_table('brand_memory',
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_memory_client_id'), ['client_id'], unique=False)

    op.create_table('brands',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('instagram_handle', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('positioning', sa.Text(), nullable=True),
    sa.Column('tone', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('visual_identity', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('locations', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('business_goals', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('words_to_avoid', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('claims_to_avoid', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('unknown_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_client_id'), ['client_id'], unique=False)

    op.create_table('competitors',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('tier', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitors_client_id'), ['client_id'], unique=False)

    op.create_table('content_ideas',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('pillar', sa.String(length=60), nullable=False),
    sa.Column('format', sa.String(length=24), nullable=False),
    sa.Column('objective', sa.String(length=40), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('viral_score', sa.Float(), nullable=True),
    sa.Column('business_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('promoted_content_item_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_ideas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_ideas_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_ideas_pillar'), ['pillar'], unique=False)

    op.create_table('content_pillars',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objective', sa.String(length=40), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('examples', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_pillars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_pillars_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_pillars_key'), ['key'], unique=False)

    op.create_table('memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_membership_user_client')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('social_accounts',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=True),
    sa.Column('ig_user_id', sa.String(length=64), nullable=True),
    sa.Column('page_id', sa.String(length=64), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_accounts_client_id'), ['client_id'], unique=False)

    op.create_table('strategies',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('pillar_mix', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('posting_frequency', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('format_split', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('objectives', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('audience_focus', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('themes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('derived_from_insights', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_client_id'), ['client_id'], unique=False)

    op.create_table('trends',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('popularity', sa.String(length=24), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('expiry_probability', sa.Float(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('fits_brand', sa.Boolean(), nullable=True),
    sa.Column('fit_reason', sa.Text(), nullable=True),
    sa.Column('recommended_adaptation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trends_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trends_status'), ['status'], unique=False)

    op.create_table('audiences',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('segment', sa.String(length=160), nullable=False),
    sa.Column('demographics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('pains', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('desires', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audiences_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audiences_client_id'), ['client_id'], unique=False)

    op.create_table('brand_assets',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_assets_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_assets_client_id'), ['client_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_client_id'), ['client_id'], unique=False)

    op.create_table('competitor_posts',
    sa.Column('competitor_id', sa.Uuid(), nullable=False),
    sa.Column('platform_post_id', sa.String(length=120), nullable=True),
    sa.Column('permalink', sa.String(length=500), nullable=True),
    sa.Column('format', sa.String(length=24), nullable=True),
    sa.Column('topic', sa.String(length=300), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('engagement_estimate', sa.Float(), nullable=True),
    sa.Column('observed_pattern', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitor_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_posts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_posts_competitor_id'), ['competitor_id'], unique=False)

    op.create_table('products',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('brand_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_client_id'), ['client_id'], unique=False)

    op.create_table('services',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_client_id'), ['client_id'], unique=False)

    op.create_table('content_items',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('format', sa.String(length=24), nullable=False),
    sa.Column('pillar', sa.String(length=60), nullable=False),
    sa.Column('objective', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('viral_score', sa.Float(), nullable=True),
    sa.Column('business_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('qa_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('approval_level', sa.String(length=32), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('idea_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_items_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_content_items_client_pillar', ['client_id', 'pillar'], unique=False)
        batch_op.create_index('ix_content_items_client_scheduled', ['client_id', 'scheduled_for'], unique=False)
        batch_op.create_index('ix_content_items_client_status', ['client_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_format'), ['format'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_status'), ['status'], unique=False)

    op.create_table('approvals',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_content_item_id'), ['content_item_id'], unique=False)

    op.create_table('calendar_entries',
    sa.Column('content_item_id', sa.Uuid(), nullable=True),
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot_label', sa.String(length=60), nullable=True),
    sa.Column('format', sa.String(length=24), nullable=False),
    sa.Column('pillar', sa.String(length=60), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_entries', schema=None) as batch_op:
        batch_op.create_index('ix_calendar_client_time', ['client_id', 'scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_entries_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_entries_content_item_id'), ['content_item_id'], unique=False)

    op.create_table('comments',
    sa.Column('content_item_id', sa.Uuid(), nullable=True),
    sa.Column('platform_comment_id', sa.String(length=120), nullable=True),
    sa.Column('author_handle', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('suggested_reply', sa.Text(), nullable=True),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_content_item_id'), ['content_item_id'], unique=False)

    op.create_table('content_assets',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_assets_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_assets_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_assets_content_item_id'), ['content_item_id'], unique=False)

    op.create_table('content_memory',
    sa.Column('content_item_id', sa.Uuid(), nullable=True),
    sa.Column('topic', sa.String(length=300), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('topic_fingerprint', sa.String(length=500), nullable=False),
    sa.Column('hook_fingerprint', sa.String(length=500), nullable=True),
    sa.Column('pillar', sa.String(length=60), nullable=False),
    sa.Column('format', sa.String(length=24), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('performance_index', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_memory_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_content_memory_client_pillar', ['client_id', 'pillar'], unique=False)
        batch_op.create_index('ix_content_memory_client_topic', ['client_id', 'topic_fingerprint'], unique=False)

    op.create_table('content_variants',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_variants_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_variants_content_item_id'), ['content_item_id'], unique=False)

    op.create_table('leads',
    sa.Column('handle', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('intent', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('requested_service', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attributed_content_item_id', sa.Uuid(), nullable=True),
    sa.Column('contact', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attributed_content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)

    op.create_table('scheduled_posts',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('social_account_id', sa.Uuid(), nullable=True),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_posts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_posts_content_item_id'), ['content_item_id'], unique=False)
        batch_op.create_index('ix_scheduled_posts_due', ['status', 'publish_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_posts_status'), ['status'], unique=False)

    op.create_table('dm_threads',
    sa.Column('platform_thread_id', sa.String(length=120), nullable=True),
    sa.Column('handle', sa.String(length=120), nullable=True),
    sa.Column('intent', sa.String(length=40), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('last_message', sa.Text(), nullable=True),
    sa.Column('suggested_reply', sa.Text(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('messages', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dm_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dm_threads_client_id'), ['client_id'], unique=False)

    op.create_table('published_posts',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_post_id', sa.Uuid(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_post_id', sa.String(length=120), nullable=False),
    sa.Column('permalink', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_post_id'], ['scheduled_posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('published_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_published_posts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_posts_content_item_id'), ['content_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_posts_platform_post_id'), ['platform_post_id'], unique=False)

    op.create_table('analytics_snapshots',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('published_post_id', sa.Uuid(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('follows', sa.Integer(), nullable=False),
    sa.Column('profile_visits', sa.Integer(), nullable=False),
    sa.Column('link_clicks', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('avg_watch_time_s', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_post_id'], ['published_posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_content_item_id'), ['content_item_id'], unique=False)
        batch_op.create_index('ix_snapshots_client_time', ['client_id', 'captured_at'], unique=False)
        batch_op.create_index('ix_snapshots_item_time', ['content_item_id', 'captured_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_item_time')
        batch_op.drop_index('ix_snapshots_client_time')
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_client_id'))

    op.drop_table('analytics_snapshots')
    with op.batch_alter_table('published_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_published_posts_platform_post_id'))
        batch_op.drop_index(batch_op.f('ix_published_posts_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_published_posts_client_id'))

    op.drop_table('published_posts')
    with op.batch_alter_table('dm_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dm_threads_client_id'))

    op.drop_table('dm_threads')
    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_status'))
        batch_op.drop_index('ix_scheduled_posts_due')
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_client_id'))

    op.drop_table('scheduled_posts')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_client_id'))

    op.drop_table('leads')
    with op.batch_alter_table('content_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_variants_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_content_variants_client_id'))

    op.drop_table('content_variants')
    with op.batch_alter_table('content_memory', schema=None) as batch_op:
        batch_op.drop_index('ix_content_memory_client_topic')
        batch_op.drop_index('ix_content_memory_client_pillar')
        batch_op.drop_index(batch_op.f('ix_content_memory_client_id'))

    op.drop_table('content_memory')
    with op.batch_alter_table('content_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_assets_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_content_assets_client_id'))
        batch_op.drop_index(batch_op.f('ix_content_assets_asset_id'))

    op.drop_table('content_assets')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_comments_client_id'))
        batch_op.drop_index(batch_op.f('ix_comments_classification'))

    op.drop_table('comments')
    with op.batch_alter_table('calendar_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_entries_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_entries_client_id'))
        batch_op.drop_index('ix_calendar_client_time')

    op.drop_table('calendar_entries')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_client_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_items_status'))
        batch_op.drop_index(batch_op.f('ix_content_items_format'))
        batch_op.drop_index('ix_content_items_client_status')
        batch_op.drop_index('ix_content_items_client_scheduled')
        batch_op.drop_index('ix_content_items_client_pillar')
        batch_op.drop_index(batch_op.f('ix_content_items_client_id'))

    op.drop_table('content_items')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_client_id'))
        batch_op.drop_index(batch_op.f('ix_services_brand_id'))

    op.drop_table('services')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_client_id'))
        batch_op.drop_index(batch_op.f('ix_products_brand_id'))

    op.drop_table('products')
    with op.batch_alter_table('competitor_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_posts_competitor_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_posts_client_id'))

    op.drop_table('competitor_posts')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_client_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('brand_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_assets_client_id'))
        batch_op.drop_index(batch_op.f('ix_brand_assets_brand_id'))

    op.drop_table('brand_assets')
    with op.batch_alter_table('audiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audiences_client_id'))
        batch_op.drop_index(batch_op.f('ix_audiences_brand_id'))

    op.drop_table('audiences')
    with op.batch_alter_table('trends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trends_status'))
        batch_op.drop_index(batch_op.f('ix_trends_client_id'))

    op.drop_table('trends')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_client_id'))

    op.drop_table('strategies')
    with op.batch_alter_table('social_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_accounts_client_id'))

    op.drop_table('social_accounts')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_client_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('content_pillars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_pillars_key'))
        batch_op.drop_index(batch_op.f('ix_content_pillars_client_id'))

    op.drop_table('content_pillars')
    with op.batch_alter_table('content_ideas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_ideas_pillar'))
        batch_op.drop_index(batch_op.f('ix_content_ideas_client_id'))

    op.drop_table('content_ideas')
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitors_client_id'))

    op.drop_table('competitors')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_client_id'))

    op.drop_table('brands')
    with op.batch_alter_table('brand_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_memory_client_id'))

    op.drop_table('brand_memory')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_client_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_shoot_group'))
        batch_op.drop_index(batch_op.f('ix_assets_footage_type'))
        batch_op.drop_index(batch_op.f('ix_assets_client_id'))

    op.drop_table('assets')
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_insights_client_id'))

    op.drop_table('ai_insights')
    with op.batch_alter_table('ai_activity_log', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_log_client_time')
        batch_op.drop_index('ix_ai_log_agent_time')
        batch_op.drop_index(batch_op.f('ix_ai_activity_log_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_ai_activity_log_client_id'))
        batch_op.drop_index(batch_op.f('ix_ai_activity_log_agent'))

    op.drop_table('ai_activity_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_supabase_uid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_slug'))

    op.drop_table('clients')
    # ### end Alembic commands ###
